import sys

from django.conf import settings
from django.core.management.base import NoArgsCommand, CommandError


class Command(NoArgsCommand):
    help = 'Validate settings'

    def handle(self, **options):
        is_valid = True
        try:
            parser = settings.__SCHEMACONFIGPARSER__
        except AttributeError:
            # this is a normal settings file, not generated by schemaconfig
            parser = None

        if parser is not None:
            is_valid = parser.is_valid()

        if not is_valid:
            raise CommandError("Settings did not validate against schema")

        return "Settings appear to be fine"

